version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - dev
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 256m

  api:
    image: ${DOCKER_USERNAME}/easy-english-api
    container_name: easy_english_api
    environment:
      ConnectionStrings__Postgres: "${DB_CONNECTION_STRING}"
      WebBaseUrl: ${WEB_BASE_URL}
      Auth__Key: ${AUTH_KEY}
      Auth__Issuer: ${AUTH_ISSUER}
      Auth__Audience: ${AUTH_AUDIENCE}
      Hash__Pepper: ${HASH_PEPPER}
      Aes__Key: ${AES_KEY}
      Aes__IV: ${AES_IV}
      Email__Host: ${EMAIL_HOST}
      Email__Port: ${EMAIL_PORT}
      Email__EmailTo: ${EMAIL_TO}
      Email__Password: ${EMAIL_PASSWORD}
    depends_on:
      - db
    ports:
      - "8081:8080"
    restart: always
    networks:
      - dev
    deploy:
      resources:
        limits:
          memory: 256m
  
  client:
    image: ${DOCKER_USERNAME}/easy-english-ui
    container_name: easy_english_ui
    depends_on:
      - api
    ports:
      - "8001:80"
    restart: always
    networks:
      - dev
    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  pgdata:
  
networks:
  dev:
    driver: bridge