version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - dev
    deploy:
      resources:
        limits:
          memory: 256m

  api:
    build:
      context: .
      dockerfile: EasyEnglish/Dockerfile
    container_name: easy_english_api
    environment:
      ConnectionStrings__Postgres: "${DB_CONNECTION_STRING}"
      WebBaseUrl: ${WEB_BASE_URL}
    depends_on:
      - db
    ports:
      - "8081:8080"
    restart: always
    networks:
      - dev
    deploy:
      resources:
        limits:
          memory: 256m
  
  client:
    build:
      context: .
      dockerfile: EasyEnglish.UI/Dockerfile
    container_name: easy_english_ui
    depends_on:
      - api
    ports:
      - "8001:80"
    restart: always
    networks:
      - dev
    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  pgdata:
  
networks:
  dev:
    driver: bridge